/* Generated By:JavaCC: Do not edit this line. MiniJavaConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 11;
  /** RegularExpression Id. */
  int VOID = 12;
  /** RegularExpression Id. */
  int STRING = 13;
  /** RegularExpression Id. */
  int BOOLEAN = 14;
  /** RegularExpression Id. */
  int THIS = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int MAIN = 18;
  /** RegularExpression Id. */
  int LENGTH = 19;
  /** RegularExpression Id. */
  int PRINT = 20;
  /** RegularExpression Id. */
  int IF = 21;
  /** RegularExpression Id. */
  int NEW = 22;
  /** RegularExpression Id. */
  int ELSE = 23;
  /** RegularExpression Id. */
  int CLASS = 24;
  /** RegularExpression Id. */
  int WHILE = 25;
  /** RegularExpression Id. */
  int FOR = 26;
  /** RegularExpression Id. */
  int PUBLIC = 27;
  /** RegularExpression Id. */
  int RETURN = 28;
  /** RegularExpression Id. */
  int STATIC = 29;
  /** RegularExpression Id. */
  int EXTENDS = 30;
  /** RegularExpression Id. */
  int LPAREN = 31;
  /** RegularExpression Id. */
  int RPAREN = 32;
  /** RegularExpression Id. */
  int LBRACKET = 33;
  /** RegularExpression Id. */
  int RBRACKET = 34;
  /** RegularExpression Id. */
  int LBRACE = 35;
  /** RegularExpression Id. */
  int RBRACE = 36;
  /** RegularExpression Id. */
  int COMMA = 37;
  /** RegularExpression Id. */
  int DOT = 38;
  /** RegularExpression Id. */
  int SEMI = 39;
  /** RegularExpression Id. */
  int ADD = 40;
  /** RegularExpression Id. */
  int SUB = 41;
  /** RegularExpression Id. */
  int MULT = 42;
  /** RegularExpression Id. */
  int DIV = 43;
  /** RegularExpression Id. */
  int AND = 44;
  /** RegularExpression Id. */
  int NOT = 45;
  /** RegularExpression Id. */
  int LESS = 46;
  /** RegularExpression Id. */
  int ASSIGN = 47;
  /** RegularExpression Id. */
  int NUM = 48;
  /** RegularExpression Id. */
  int IDENTIFIER = 49;
  /** RegularExpression Id. */
  int LETTER = 50;
  /** RegularExpression Id. */
  int DIGIT = 51;
  /** RegularExpression Id. */
  int STRING_LITERAL = 52;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MLComment = 1;
  /** Lexical state. */
  int SLComment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"//\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "\"int\"",
    "\"void\"",
    "\"String\"",
    "\"boolean\"",
    "\"this\"",
    "\"true\"",
    "\"false\"",
    "\"main\"",
    "\"length\"",
    "\"System.out.println\"",
    "\"if\"",
    "\"new\"",
    "\"else\"",
    "\"class\"",
    "\"while\"",
    "\"for\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"extends\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"!\"",
    "\"<\"",
    "\"=\"",
    "<NUM>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<STRING_LITERAL>",
  };

}
